name: Connect to Azure and List Resources

on:
  push:
    branches:
      - main 
jobs:
  connect-to-azure:
    runs-on: ubuntu-latest
    
      - name: Azure Login
        uses: Azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_SP_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_SP_TENANT_ID }}
      
      - name: Run Azure commands using the authenticated identity
        run: |
          az resource list
